apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-deployment-test
  namespace: default
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate:         
        '{
            "type": "public",
            "bandwidth_name": "cce-jenkins-demo-deployment-test",
            "bandwidth_chargemode": "bandwidth",
            "bandwidth_size": 5,
            "bandwidth_sharetype": "PER",
            "eip_type": "5_bgp"
        }'

spec:
  selector:
    app: jenkins-demo-deployment-test
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 1323
  type: LoadBalancer
