apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-deployment-service
spec:
  selector:
    app: jenkins-demo-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 1323
  type: LoadBalancer
